### ISSUE TITLE
Missing "esp_system.h" on v2.0.1

### ISSUE THREAD

**Issue by LordParsley** [Seeed-Studio/Seeed_Arduino_mbedtls#3]
**Describe the bug**
When following the Wio Terminal [network guidelines](https://wiki.seeedstudio.com/Wio-Terminal-Network-Overview/#3-install-the-seeed_arduino_mbedtls):

* ✅  the linked [dev branch](https://github.com/Seeed-Studio/Seeed_Arduino_mbedtls/tree/dev) of this library works,
* ❌  but using the latest tagged `v2.0.1` on `master` fails:

```
/Seeed_Arduino_mbedtls/src/port/esp_hardware.c:11:10: fatal error: esp_system.h: No such file or directory
 #include <esp_system.h>
          ^~~~~~~~~~~~~~
compilation terminated.
exit status 1
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Wio Terminal [Github tutorial](https://wiki.seeedstudio.com/Wio-Terminal-Reading-Github/).
2. Follow directions to install network dependencies.
3. Use the `master` branch of https://github.com/Seeed-Studio/Seeed_Arduino_mbedtls on `v2.0.1` instead of `dev`.
4. Verify or compile sketch in Arduino IDE.

**Expected behaviour**
The sketch compiles successfully on `v2.0.1`.

**Comment by Pillar1989** [comment]
@lakshanthad  Have you tested it since you merged?

**Comment by lakshanthad** [comment]
Hi @LordParsley,

You are required to use the `dev` branch if you are using the new eRPC firmware 

`master` branch can only be used if you are using the old AT firmware

Please try again with the `dev` branch and let me know the results

Best Regards,
Lakshantha

**Comment by LordParsley** [comment]
Thanks, @lakshanthad .

As I mentioned in my original post, `dev` is 100%.
> ✅ the linked dev branch of this library works

I guess I was just wondering why the latest tag v2.0.1 wasn't working but maintaining the older AT firmware makes sense.

I'll close this ticket! Thanks for the feedback.
